import { createFileRoute } from "@tanstack/react-router";
import { ProductPage } from "@/components/pages/product-page";
const methods = [
  { title: "Problem", text: "Coarse rainfall information does not fully represent local variation needed for Panchayat-level interpretation." },
  { title: "Geographic resolution", text: "India-wide administrative exploration is separate from the current model coverage centered on Dhanbad District, Jharkhand." },
  { title: "Data inputs", text: "The project pipeline supports reference rainfall, temperature, humidity, wind, ET, elevation, slope, landcover, and backend-generated temporal features." },
  { title: "Reference rainfall", text: "A project reference or coarse rainfall dataset provides the baseline input. It is never automatically labelled as an observation." },
  { title: "Local features", text: "Geographic and meteorological attributes provide local context at the Panchayat scale." },
  { title: "Residual downscaling", text: "The backend learns a residual adjustment to the reference rainfall rather than recreating feature engineering in the browser." },
  { title: "Model", text: "Ridge Residual predicts Panchayat rainfall. The current frontend does not claim onset, break, future weather, or calibrated uncertainty outputs." },
  { title: "Validation", text: "Validated performance metrics will be shown only when supplied by the evaluation pipeline." },
  { title: "Baseline comparison", text: "Reference and downscaled values are compared directly; their difference is not described as individual-prediction accuracy." },
  { title: "Limitations", text: "Model results require the FastAPI service. Panchayat records are metadata-only where verified boundary polygons are unavailable." },
  { title: "Data provenance", text: "Administrative boundaries, project Panchayat metadata, rainfall datasets, and model output are identified separately." },
  { title: "Decision-support use", text: "Outputs support localized rainfall interpretation and planning; they are not official forecasts or government warnings." },
];
export const Route = createFileRoute("/methodology")({ head: () => ({ meta: [{ title: "Rainfall Downscaling Methodology — MonsoonScope" }, { name: "description", content: "Understand MonsoonScope's Ridge Residual Panchayat rainfall-downscaling approach, inputs, limits, and provenance." }, { property: "og:title", content: "Rainfall Downscaling Methodology — MonsoonScope" }, { property: "og:description", content: "How reference rainfall and local features support Panchayat-level rainfall intelligence." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: () => <ProductPage eyebrow="Scientific basis" title="Rainfall downscaling methodology" description="MonsoonScope uses Ridge Residual to transform coarse/reference rainfall and local Panchayat features into localized rainfall intelligence for the Dhanbad demonstration area."><div className="mb-8 scientific-panel p-5"><p className="metric-label">Model pathway</p><p className="mt-3 font-mono text-sm leading-8 text-primary">REFERENCE RAINFALL → LOCAL PANCHAYAT FEATURES → RESIDUAL LEARNING → RIDGE RESIDUAL → PANCHAYAT RAINFALL → COMPARISON</p></div><div className="grid border border-border bg-card md:grid-cols-2 xl:grid-cols-3">{methods.map((method, index) => <article className={`p-6 ${index > 0 ? "border-t border-border" : ""} ${index % 2 ? "md:border-l" : ""} ${index > 1 ? "md:border-t" : ""} ${index % 3 ? "xl:border-l" : "xl:border-l-0"}`} key={method.title}><p className="font-mono text-xs text-primary">{String(index + 1).padStart(2, "0")}</p><h2 className="mt-3 text-lg font-bold">{method.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{method.text}</p></article>)}</div></ProductPage> });