/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MapRouteImport } from './routes/map'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as RainfallRouteImport } from './routes/rainfall'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const RainfallRoute = RainfallRouteImport.update({
  id: '/rainfall',
  path: '/rainfall',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/predictions': typeof PredictionsRoute
  '/rainfall': typeof RainfallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/predictions': typeof PredictionsRoute
  '/rainfall': typeof RainfallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/predictions': typeof PredictionsRoute
  '/rainfall': typeof RainfallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/history'
    | '/map'
    | '/methodology'
    | '/predictions'
    | '/rainfall'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/history'
    | '/map'
    | '/methodology'
    | '/predictions'
    | '/rainfall'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/history'
    | '/map'
    | '/methodology'
    | '/predictions'
    | '/rainfall'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  HistoryRoute: typeof HistoryRoute
  MapRoute: typeof MapRoute
  MethodologyRoute: typeof MethodologyRoute
  PredictionsRoute: typeof PredictionsRoute
  RainfallRoute: typeof RainfallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rainfall': {
      id: '/rainfall'
      path: '/rainfall'
      fullPath: '/rainfall'
      preLoaderRoute: typeof RainfallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  HistoryRoute: HistoryRoute,
  MapRoute: MapRoute,
  MethodologyRoute: MethodologyRoute,
  PredictionsRoute: PredictionsRoute,
  RainfallRoute: RainfallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
